### ISSUE TITLE
Interaction Attachments

### ISSUE THREAD

**Issue by Crispy-Cream** [GmBodhi/shandler#17]
**Is your feature request related to a problem? If so, please describe. If not, put N/A**
If you try to send a discord.js MessageAttachment it will throw an error.

**Describe the solution you'd like**
Like 
```js
interaction.reply("", { embed: embed });
```
have 
```js
let attachment = new Discord.MessageAttachment(buffer, "burn.png");
interaction.reply("", { attachment: attachment });
```

**Describe alternatives you've considered**
I can't think of a better alternative. 

**Additional context**

**Comment by GmBodhi** [comment]
I'll make a pr

**Comment by GmBodhi** [comment]
This may work: ```js
let attachment = new Discord.MessageAttachment(buffer, "burn.png");
interaction.reply("", { files: [ attachment ] });
```

**Comment by GmBodhi** [comment]
Feature added.
