### ISSUE TITLE
Abillity to add buttons to normal messages

### ISSUE THREAD

**Issue by STR1KE6969** [GmBodhi/shandler#18]
**Is your feature request related to a problem? If so, please describe. If not, put N/A**
N/A

**Describe the solution you'd like**
A cool thing will be to add buttons to normal messages

**Describe alternatives you've considered**
undefined

**Additional context**
null

**Comment by Crispy-Cream** [comment]
- Requested Reopen on Discord to edit.

**Comment by GmBodhi** [comment]
I don't think it's related to interactions

**Comment by GmBodhi** [comment]
Hereby, closing the issue. If you want to continue in this thread, please reopen.
