### ISSUE TITLE
Unexpected Token '?'

### ISSUE THREAD

**Issue by Zerrain3** [GmBodhi/shandler#6]
SyntaxError: Unexpected token '?'

        this.messageRefID = message_reference.message_id ?? "@original"

node_modules/shandler/js/FInteraction.js:59

**Comment by GmBodhi** [comment]
You should probably consider updating your node version to 14.x+

**Comment by GmBodhi** [comment]
you can also as your queries in the [support server](https://discord.gg/tMWmEJFq4m)
[Node.js 14.17.0 LTS](https://nodejs.org/dist/v14.17.0/node-v14.17.0-x64.msi)

**Comment by Zerrain3** [comment]
im using replit
how do i upgrade node version on it?

**Comment by GmBodhi** [comment]
You can create a bash repl and use node.js in it.

**Comment by Zerrain3** [comment]
so i should make a bash repl and copy the code?

**Comment by GmBodhi** [comment]
> 
> 
> so I should make a bash repl and copy the code?

Just make a new bash repl and make a file named `main.sh` ```bash
node .
```
and a `.replit` file ```txt
language="bash"
run="sh main.sh"```
then you'll be good to go.

**Comment by Zerrain3** [comment]
i put node . in main.sh?

**Comment by GmBodhi** [comment]
Mhm
